### ISSUE TITLE
Broken install via pip

### ISSUE THREAD

**Issue by SuibianP** [oldcai/chinese-slugify#1]
Firstly, many thanks for the package, which can provide great convenience for the slugification of Chinese text.

However, there seems to be some issue regarding the installation via pip package installer.

When trying to install via pip using `pip install chinese-slugify`, the installation failed with:
```
ERROR: Could not find a version that satisfies the requirement chinese-slugify (from versions: none)
ERROR: No matching distribution found for chinese-slugify
```
With verbose output, it is revealed that:
```
Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/17/19/f9a3882878f18165a09f5ded7d2964fa6c527ba48f864ed086d247df0999/chinese_slugify-0.1.0-py2.7.egg#sha256=9971e16d120d05511f2799f5b2ebb0cb6a3b69bc3993095b9bb5c0d765fb9228 (from https://pypi.org/simple/chinese-slugify/)
```
It seems that this is caused by [egg format being unsupported](https://github.com/pypa/pip/issues/492).

Is it possible that you may repackage [in line with the guidelines](https://packaging.python.org/tutorials/packaging-projects/) and update on PyPI?

**Comment by oldcai** [comment]
Hi, what version of OS and python are you using?

**Comment by SuibianP** [comment]
> Hi, what version of OS and python are you using?

Ubuntu 18.04.5 LTS

Python 2.7.17 & 3.6.9 (both fails with identical error)

**Comment by oldcai** [comment]
Would you like to have another try? I've updated the pip package.

Note that please update from pypi.org instead of other mirrors as it's a brand new one.

**Comment by SuibianP** [comment]
> Would you like to have another try? I've updated the pip package.
> 
> Note that please update from pypi.org instead of other mirrors as it's a brand new one.

Thank you very much for the quick response! The installation now seems fine with pip3, but still not with pip2, which fails with the following info (excerpt)
```
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lijxJe/chinese-slugify/setup.py", line 19, in <module>
        install_requires = [i.strip() for i in open("requirements.txt").readlines()]
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by oldcai** [comment]
Hi, sorry I haven't got time right now, I'll look into it on Sunday.
Anyway, PRs are welcomed.

**Comment by SuibianP** [comment]
> Hi, sorry I haven't got time right now, I'll look into it on Sunday.
> Anyway, PRs are welcomed.

It seems that the installation goes fine when I tested in a venv just now; might be some hiccup on the server-side yesterday.
I am currently working on Python 3 compatibility and will submit a PR when I finish.
Thank you very much for your response and have a good weekend ahead! 😃
